name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Or use @v4 if that is confirmed to exist for your use case.
      - name: configure
        run: ./configure
      - name: build
        run: make
      - name: test
        run: make check
      - name: distcheck
        run: make distcheck
      - name: clean
        run: make clean
